--liquibase formatted sql
--changeset liquibase:0001.create_book
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'BOOK' LIMIT 1;
CREATE TABLE BOOK (
	ID CHAR(36) NOT NULL,
	TITLE VARCHAR(1000) NOT NULL,
    AVERAGE_RATING FLOAT NULL,
    ISBN varchar(100) NULL,
    ISBN13 varchar(100) NULL,
    LANGUAGE_CODE varchar(100) NULL,
    NUM_PAGES INT UNSIGNED NULL,
    RATINGS_COUNT INT UNSIGNED NULL,
    PUBLICATION_DATE DATE NULL,
    PUBLISHER varchar(200) NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;