version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
    - 3060:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: jpa
      MYSQL_USER: jpa
      MYSQL_PASSWORD: jpa
volumes:
  db_data: {}
